import prisma from '../../config/prisma.js';

export interface AttendanceSettings {
  officeStartTime: string;
  officeEndTime: string;
  gracePeriod: number;
  autoCheckoutEnabled: boolean;
  maxWorkingHours: number;
  lateThreshold: number;
  earlyDepartureThreshold: number;
}

let cachedSettings: any = null;
let settingsCacheTime = 0;

export const getOrCreateSettings = async (): Promise<any> => {
  const now = Date.now();
  if (cachedSettings && now - settingsCacheTime < 60000) {
    return cachedSettings;
  }

  let settings = await prisma.facultyattendancesettings.findFirst();
  if (!settings) {
    settings = await prisma.facultyattendancesettings.create({
      data: {
        officestarttime: '09:00',
        officeendtime: '17:00',
        graceperiod: 30,
        autocheckoutenabled: true,
        maxworkinghours: 12.0,
        latethreshold: 15,
        earlydeparturethreshold: 15,
      },
    });
  }
  cachedSettings = settings;
  settingsCacheTime = now;
  return settings;
};

export const updateSettings = async (data: Partial<AttendanceSettings>): Promise<any> => {
  const current = await getOrCreateSettings();
  cachedSettings = null; // Invalidate cache
  return await prisma.facultyattendancesettings.update({
    where: { id: current.id },
    data: {
      officestarttime: data.officeStartTime,
      officeendtime: data.officeEndTime,
      graceperiod: data.gracePeriod,
      autocheckoutenabled: data.autoCheckoutEnabled,
      maxworkinghours: data.maxWorkingHours,
      latethreshold: data.lateThreshold,
      earlydeparturethreshold: data.earlyDepartureThreshold,
      updatedat: new Date(),
    },
  });
};

// Helper: Convert time string "HH:MM" on a specific date to Date object
const parseTimeString = (date: Date, timeStr: string): Date => {
  const [hours, minutes] = timeStr.split(':').map(Number);
  const result = new Date(date);
  result.setHours(hours, minutes, 0, 0);
  return result;
};

// Auto check-out runner (detects missing check-outs from yesterday/earlier and updates them)
export const processAutoCheckouts = async () => {
  const settings = await getOrCreateSettings();
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  // Find all active attendance records before today where check-out is missing (null)
  const openRecords = await prisma.facultyattendance.findMany({
    where: {
      checkouttime: null,
      attendancedate: {
        lt: today,
      },
    },
  });

  if (openRecords.length === 0) {
    return;
  }

  const systemUser = await prisma.user.findFirst({
    where: {
      username: 'user3@edmin.com', // Admin user
    },
  });
  const systemUserId = systemUser?.userid || 1;

  for (const record of openRecords) {
    const recordDate = new Date(record.attendancedate);
    const officeEnd = parseTimeString(recordDate, settings.officeendtime);
    
    // Auto check-out time = Office End Time + Grace Period (in minutes)
    const autoCheckoutTime = new Date(officeEnd.getTime() + settings.graceperiod * 60 * 1000);
    const hours = (autoCheckoutTime.getTime() - new Date(record.checkintime!).getTime()) / (1000 * 60 * 60);

    await prisma.$transaction(async (tx) => {
      if (settings.autocheckoutenabled) {
        // Auto check-out
        const updated = await tx.facultyattendance.update({
          where: { facultyattendanceid: record.facultyattendanceid },
          data: {
            checkouttime: autoCheckoutTime,
            status: 'Auto Checked Out',
            workinghours: Math.min(hours, settings.maxworkinghours),
            isautocheckout: true,
            updatedat: new Date(),
          },
        });

        await tx.facultyattendanceauditlog.create({
          data: {
            attendanceid: record.facultyattendanceid,
            action: 'AUTO_CHECKOUT',
            oldcheckin: record.checkintime,
            newcheckin: record.checkintime,
            oldcheckout: null,
            newcheckout: autoCheckoutTime,
            reason: 'Forgot check-out (auto check-out generated by system)',
            performedby: systemUserId,
            performedrole: 'ADMIN',
            ipaddress: '127.0.0.1',
            device: 'System Service',
          },
        });
      } else {
        // Just set Forgot Check Out
        await tx.facultyattendance.update({
          where: { facultyattendanceid: record.facultyattendanceid },
          data: {
            status: 'Forgot Check Out',
            updatedat: new Date(),
          },
        });
      }
    });
  }
};

export const validateCard = async (cardNumber: string) => {
  const facultyMember = await prisma.faculty.findFirst({
    where: {
      cardnumber: cardNumber,
      isactive: true,
      user: {
        accountStatus: 'ACTIVE',
      },
    },
    include: {
      user: true,
      department: true,
    },
  });

  return facultyMember;
};

export const processCardTap = async (cardNumber: string, readerId: string = 'READER-01'): Promise<any> => {
  // First run auto check-outs so everything is in a clean state
  await processAutoCheckouts();

  const facultyMember = await validateCard(cardNumber);
  if (!facultyMember) {
    throw new Error('Invalid or unassigned smart card');
  }

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const settings = await getOrCreateSettings();
  const now = new Date();

  // Find today's attendance record
  const existing = await prisma.facultyattendance.findFirst({
    where: {
      facultyid: facultyMember.facultyid,
      attendancedate: today,
    },
  });

  return await prisma.$transaction(async (tx) => {
    if (!existing) {
      // 1. Check-In Flow
      const officeStart = parseTimeString(today, settings.officestarttime);
      const isLate = now.getTime() > officeStart.getTime() + settings.latethreshold * 60 * 1000;
      const status = isLate ? 'Late Arrival' : 'Currently Working';

      const attendanceRecord = await tx.facultyattendance.create({
        data: {
          facultyid: facultyMember.facultyid,
          attendancedate: today,
          checkintime: now,
          status,
          workinghours: 0,
          attendancesource: 'CARD',
          cardreaderid: readerId,
          islate: isLate,
          isearlydeparture: false,
          isautocheckout: false,
        },
      });

      await tx.facultyattendanceauditlog.create({
        data: {
          attendanceid: attendanceRecord.facultyattendanceid,
          action: 'CHECKIN',
          oldcheckin: null,
          newcheckin: now,
          oldcheckout: null,
          newcheckout: null,
          reason: 'Smart card tap check-in',
          performedby: facultyMember.userid,
          performedrole: 'FACULTY',
          ipaddress: '127.0.0.1',
          device: `Card Reader (${readerId})`,
        },
      });

      return {
        action: 'CHECKIN',
        record: attendanceRecord,
        faculty: facultyMember,
      };
    } else {
      // 2. Check-Out Flow
      if (existing.checkouttime !== null) {
        // Already checked out today: re-open check-in session for re-entry or simulator testing
        const officeStart = parseTimeString(today, settings.officestarttime);
        const isLate = now.getTime() > officeStart.getTime() + settings.latethreshold * 60 * 1000;
        const status = isLate ? 'Late Arrival' : 'Currently Working';

        const attendanceRecord = await tx.facultyattendance.update({
          where: { facultyattendanceid: existing.facultyattendanceid },
          data: {
            checkintime: now,
            checkouttime: null,
            status,
            workinghours: 0,
            attendancesource: 'CARD',
            cardreaderid: readerId,
            islate: isLate,
            isearlydeparture: false,
            isautocheckout: false,
            updatedat: new Date(),
          },
        });

        await tx.facultyattendanceauditlog.create({
          data: {
            attendanceid: attendanceRecord.facultyattendanceid,
            action: 'CHECKIN',
            oldcheckin: existing.checkintime,
            newcheckin: now,
            oldcheckout: existing.checkouttime,
            newcheckout: null,
            reason: 'Smart card tap check-in (re-entry)',
            performedby: facultyMember.userid,
            performedrole: 'FACULTY',
            ipaddress: '127.0.0.1',
            device: `Card Reader (${readerId})`,
          },
        });

        return {
          action: 'CHECKIN',
          record: attendanceRecord,
          faculty: facultyMember,
        };
      }

      // Perform checkout
      const checkInTime = new Date(existing.checkintime!);
      const hours = (now.getTime() - checkInTime.getTime()) / (1000 * 60 * 60);

      const officeEnd = parseTimeString(today, settings.officeendtime);
      const isEarly = now.getTime() < officeEnd.getTime() - settings.earlydeparturethreshold * 60 * 1000;
      
      const status = isEarly ? 'Early Departure' : 'Present';

      const attendanceRecord = await tx.facultyattendance.update({
        where: { facultyattendanceid: existing.facultyattendanceid },
        data: {
          checkouttime: now,
          status,
          workinghours: Math.min(hours, settings.maxworkinghours),
          isearlydeparture: isEarly,
          updatedat: new Date(),
        },
      });

      await tx.facultyattendanceauditlog.create({
        data: {
          attendanceid: attendanceRecord.facultyattendanceid,
          action: 'CHECKOUT',
          oldcheckin: existing.checkintime,
          newcheckin: existing.checkintime,
          oldcheckout: null,
          newcheckout: now,
          reason: 'Smart card tap check-out',
          performedby: facultyMember.userid,
          performedrole: 'FACULTY',
          ipaddress: '127.0.0.1',
          device: `Card Reader (${readerId})`,
        },
      });

      return {
        action: 'CHECKOUT',
        record: attendanceRecord,
        faculty: facultyMember,
      };
    }
  });
};
